services:
  postgres:
    image: postgres:16-alpine
    container_name: genposter-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "040904"
      POSTGRES_DB: image_metadata_api
    ports:
      - "5433:5432"
    volumes:
      - genposter_pgdata:/var/lib/postgresql/data

volumes:
  genposter_pgdata: